server:
  port: 8080
spring:
  profiles:
    active: dev   #启用开发环境
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  comfyui:
  comfyui:
    host: 127.0.0.1 # 主机地址 默认127.0.0.1
    port: 8188  # comfyui端口号 默认8188
    client-id: 1146446176
    auto-clear-task: true # 提交绘图任务时，如果ComfyUi内部有非当前服务提交的任务时是否自动取消
    queue:
      type: thread
    input-path: /Users/mashiro/ComfyUI/input
  #数据库配置
  datasource:
    driver-class-name: ${draw.datasource.driver-class-name}
    url: jdbc:mysql://${draw.datasource.host}:${draw.datasource.port}/${draw.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${draw.datasource.username}
    password: ${draw.datasource.password}
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  #redis配置
  data:
    redis:
      host: ${draw.redis.host}
      port: ${draw.redis.port}
      database: ${draw.redis.database}
      password: ${draw.redis.password}
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0


# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #用于打印框架生成的sql语句，便于调试
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(配置后可以忽略不配置步骤二)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# minio配置
minio:
  endpoint: http://${draw.minio.host}:${draw.minio.port}
  access-key: ${draw.minio.access-key}
  secret-key: ${draw.minio.secret-key}
  bucket-name: ${draw.minio.bucket-name}


# swagger配置
springdoc:
  default-flat-param-object: true   # 默认展开参数
# sa-token配置
sa-token:
  # token 有效期（单位：秒），默认30天，-1代表永不过期
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  is-log: true



